### ISSUE TITLE
No ONNX file found. Exporting ONNX... Disabling attention optimization

### ISSUE THREAD

**Issue by carnivar10** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#61]
https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/54

I found the same issue in the previous issue in the link above, but the cause and solution are different, so I'm writing a new one, probably a bug

<img width="940" alt="cpt1" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/141563521/b716af50-7f66-46a2-a471-476e5d80e934">

When you change an Advanced Setting the first time you use Export Engine, the following error occurs

`Loading weights [7e9a9b674e] from C:\stable-diffusion-webui\models\Stable-diffusion\1.5\refslaveV2_v2.safetensors
Loading VAE weights specified in settings: C:\stable-diffusion-webui\models\VAE\1.5\kl-f8-anime2.ckpt
Applying attention optimization: xformers... done.
Weights loaded in 4.4s (send model to cpu: 0.7s, load weights from disk: 0.5s, apply weights to model: 2.1s, load VAE: 0.4s, move model to device: 0.7s).
Exporting 1.5_refslaveV2_v2 to TensorRT
{'sample': [(1, 4, 64, 64), (2, 4, 128, 128), (8, 4, 256, 256)], 'timesteps': [(1,), (2,), (8,)], 'encoder_hidden_states': [(1, 77, 768), (2, 77, 768), (8, 154, 768)]}
No ONNX file found. Exporting ONNX...
Disabling attention optimization
ERROR:root:
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 74, in export_onnx
    inputs = modelobj.get_sample_input(
  File "C:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\models.py", line 977, in get_sample_input
    latent_height, latent_width = self.check_dims(
  File "C:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\models.py", line 263, in check_dims
    assert (
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 135, in export_unet_to_trt
    export_onnx(
  File "C:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 129, in export_onnx
    exit()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
 `

<img width="486" alt="cpt2" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/141563521/f998dafa-68b3-4028-aab6-6f7f2c234a0c">
<img width="820" alt="cpt3" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/141563521/22192133-ad2c-4c4d-b257-e2a1135920c9">

However, if you run Export Engine with the default option, it will appear to be an error, but Unet will be created normally, and if you run a new Export Engine after changing Advanced Settings, it will be created without error.

If this is a technically required option, rather than a bug, it seems like it needs some additional clarification on the right to avoid confusion

**Comment by alexbofa** [comment]
fix: https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/pull/75

**Comment by ENHEL686** [comment]
Similarly, to use "Advanced Settings" you must first create a "deffault", otherwise the error "No ONNX file found. Exporting ONNX..."
i not use medvram flag or lowvram 
and i tried https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/pull/75#issuecomment-1771072501
This did not fix the problem

**Comment by SiuLeeBoss** [comment]
I encountered the same problem and also tried #75 (comment), but it didn't solve the problem.
My graphics card is 1070

**Comment by helloansuman** [comment]
> Similarly, to use "Advanced Settings" you must first create a "deffault", otherwise the error "No ONNX file found. Exporting ONNX..." i not use medvram flag or lowvram and i tried [#75 (comment)](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/pull/75#issuecomment-1771072501) This did not fix the problem

Remove --medvram helped

**Comment by MorrisLu-Taipei** [comment]
same error here
linux w/installed n-driver 545.84
Launching Web UI with arguments: --xformers --listen --enable-insecure-extension-access (no --medvram needed w/3090)
done >> pip install onnxruntime
done >> pip install colored

No ONNX file found. Exporting ONNX...
Traceback (most recent call last):
  File "/home/wrt/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/wrt/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/wrt/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/wrt/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/wrt/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/wrt/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/wrt/stable-diffusion-webui/extensions/Stable-Diffusion-WebUI-TensorRT/ui_trt.py", line 134, in export_unet_to_trt
    gr.Info("No ONNX file found. Exporting ONNX...  Please check the progress in the terminal.")
AttributeError: module 'gradio' has no attribute 'Info'

**Comment by MorrisLu-Taipei** [comment]
, after checked, 
Magic, gradio upgrade to gradio: 3.41.0 . IT WORKS NOW.

**Comment by HighSodium** [comment]
I was running into the same issues, even with -medvram removed. 
I updated my pytorch and xformers  (with `--reinstall-torch` and `reinstall-xformers` respectively) to update to pytorch 2.0.1 and xformers 2.0 and the default trt built successfully. 
[(](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings)

It seems to not like building with older versions, at least for me. I'm running a 4080.

**Comment by BlankFX1** [comment]
- Never used TensorRT with --medvram.
- Tried to update pytorch and xformers (while not even using it too) with --reinstall torch and --reinstall-xformers

Still getting errors ending with
`SystemExit: None` or `No ONNX file found. Exporting ONNX... Disabling attention optimization`.

**Comment by zap95421** [comment]
Try disabling different extensions. I had the Hypernetwork MonkeyPatch from a long time ago still enabled and that was causing issues with mine. Everything worked when I disabled it.
